donation/urls.py
from django.urls import path
from .views import donations, display_donators, tembak_json

urlpatterns = [
    path("donations/", donations, name="donations"),
    path("display_donators/", display_donators, name="display_donators"),
    path("tembak_json/", tembak_json, name="tembak_json"),
]

homepage/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path("", index, name="index"),
]

login/urls.py
from django.urls import path
from .views import login, logout

urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
]

newsroom/urls.py
from django.urls import path
from .views import newsroom

urlpatterns = [
    path("", newsroom, name="newsroom"),
]

team6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("register/", include(("register.urls", "register"), namespace="register"),),
    path("donation/", include(("donation.urls", "donation"), namespace="donation"),),
    path("news/", include(("newsapp.urls", "newsapp"), namespace="newsapp")),
    path("newsroom/", include(("newsroom.urls", "newsroom"), namespace="newsroom")),
    path("testimoni/", include(("testimoni.urls", "testimoni"), namespace="testimoni")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("user_login/", include(("login.urls", "login"), namespace="login")),
]

testimoni/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    indexs,
    testimoni_handler,
    tembak_json_testi,
    createtestimoni,
    showtestimoni,
)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", indexs, name="testimoni"),
    path("write_testi/", testimoni_handler, name="write_testi"),
    path("json_testi/", tembak_json_testi, name="json_testi"),
    url(r"^createtestimoni/", createtestimoni, name="createtestimoni"),
    url(r"^showtestimoni/", showtestimoni, name="showtestimoni"),
]

urlpatterns += staticfiles_urlpatterns()

homepage/models.py
# from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render


response = {}


def index(request):
    return render(request, "homepage/index.html", response)

homepage/templates/homepage/partials/footer.html
<div class="card text-center">
	<div class="card-body">
		<h5 class="card-title">Get the latest info and news</h5>
		<h5 class="card-title">about CS-Crowdfund programs and activity</h5>
		<a href="https://twitter.com/CrowdfundCs" class="fa fa-twitter-square" style="font-size:72px"></a>
		
		<a>  </a>

		<a href="https://www.instagram.com/cs.crowdfund/" class="fa fa-instagram" style="font-size:72px"></a>
	</div>
</div>

homepage/templates/homepage/partials/header.html
<nav class="navbar navbar-expand-lg mx-auto" style="background-color: #4150AF; width: 800px;">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent"
		aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon" style="color: white;"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarToggleExternalContent">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="{% url 'homepage:index' %}">Home</a>
			<a class="nav-item nav-link" href="{% url 'newsroom:newsroom' %}">Newsroom</a>
			<a class="nav-item nav-link" href="{% url 'donation:donations' %}">Donate</a>
			{%if user.is_authenticated %}
				<a class="nav-item nav-link" href="{% url 'donation:display_donators' %}">Your Donations</a>
			{% endif %}
			<a class="nav-item nav-link" href="{% url 'testimoni:testimoni' %}">Testimonials</a>
			{%if not user.is_authenticated %}
				<a class="nav-item nav-link" href="{% url 'register:index' %}">Register</a>
				<a class="nav-item nav-link" href="{% url 'login:login' %}">Login</a>
			{% else %}
				<a class="nav-item nav-link" href="{% url 'login:logout' %}">Logout</a>
			{% endif %}
			</div>
	</div>
</nav>