login/urls.py
from django.urls import path
from .views import login, logout

urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
]

register/urls.py
from django.urls import path
from .views import add_donatur, index

urlpatterns = [
    path("register/", index, name="index"),
    path("add_donatur/", add_donatur, name="add_donatur")
]

team6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("register/", include(("register.urls", "register"), namespace="register"),),
    path("donation/", include(("donation.urls", "donation"), namespace="donation"),),
    path("news/", include(("newsapp.urls", "newsapp"), namespace="newsapp")),
    path("newsroom/", include(("newsroom.urls", "newsroom"), namespace="newsroom")),
    path("testimoni/", include(("testimoni.urls", "testimoni"), namespace="testimoni")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("user_login/", include(("login.urls", "login"), namespace="login")),
]

register/models.py
from django.db import models


class Register(models.Model):
    name = models.CharField(max_length=200)
    dob = models.DateField()
    email = models.EmailField(max_length=70, null=True, blank=True)
    password = models.CharField(max_length=100)
    password_verif = models.CharField(max_length=100)

register/forms.py
from django import forms
from .models import Register


class RegisterForm(forms.ModelForm):
    widgets = {}
    widgets['name'] = forms.TextInput(attrs={"placeholder": "Enter Your Name"})
    widgets['dob'] = forms.DateInput(
        attrs={"placeholder": "yyyy-mm-dd"}, format=('%Y-%m-%d'))
    widgets['email'] = forms.EmailInput(attrs={"placeholder": "Enter Your Email"})
    widgets['password'] = forms.PasswordInput(
        attrs={"placeholder": "Enter Your Password"}, render_value=False)
    widgets['password_verif'] = forms.PasswordInput(
        attrs={"placeholder": "Enter Your Password (again)"}, render_value=False)

    name = forms.CharField(label='Name', widget=widgets['name'])
    dob = forms.DateField(label='Date of Birth',
                          widget=widgets['dob'], input_formats=('%Y-%m-%d',))
    email = forms.EmailField(label='Email', widget=widgets['email'])
    password = forms.CharField(label="Your Password", widget=widgets['password'])
    password_verif = forms.CharField(
        label="Verify Your Password", widget=widgets['password_verif'])

    class Meta:
        model = Register
        fields = [
            "name",
            "dob",
            "email",
            "password",
            "password_verif",
        ]

    def clean_password(self):
        password = self.cleaned_data.get("password")
        password_verif = self.data.get("password_verif")
        if (password != password_verif):
            raise forms.ValidationError("Your password did not match")
        return password_verif

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not Register.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError("Your email is already registered")

register/views.py
from django.shortcuts import render
from .forms import RegisterForm

response = {}


def index(request):
    form = RegisterForm
    response["form"] = form
    return render(request, "register/index.html", response)


def add_donatur(request):
    context = {}
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            form = RegisterForm()
            context["messages"] = ["Registration Success"]
        else:
            print(form.errors)

    context["form"] = form
    return render(request, "register/index.html", context)

register/templates/register/index.html
{% extends "homepage/layout/base.html" %}
{% load static %}

{% block content %}
    
<body>	
	<div id="container-fluid">
	  <div id="content">
	    <div id="photo" style="float:left">
	      <a href="http://tinypic.com?ref=miny39" target="_blank"><img style="max-width:100%;height:auto;margin-left:20px;margin-top:110px" src="http://i66.tinypic.com/miny39.jpg" class="img-fluid" border="0" alt="Image and video hosting by TinyPic"></a>
      </div>
      
      <div id="fill">
	      <div id="title" style="float">
            <h1><strong>REGISTER YOURSELF</strong></h1>
			    <h2 id="head2">Please fill in the register form</h2>
		    </div>
           
        <div class="row">
          <div class="col-md-6">
            <form id="form" style="align:center" method="POST" action="{% url 'register:add_donatur' %}"  >
              {% csrf_token %}
              <strong>{{ form.as_p }}</strong>
              <button type="submit" class="registerbtn">Register</button>
            </form>
          </div>       
        </div>

        <div class="row">
          <div class="col-md-6">
            {% if messages %}
              <ul class="messages">
              {% for message in messages %}
                <p> {{ message }} </p> 
              {% endfor %}
              </ul>
            {% endif %}
          </div>   
        </div>
      </div>
		</div>
	</div>           
</body>
{% endblock %}