login/urls.py
from django.urls import path
from .views import login, logout

urlpatterns = [
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
]

newsapp/urls.py
from django.urls import path
from .views import newsapp, newsapp2

urlpatterns = [
    path("palu/", newsapp, name="newsapp"),
    path("lombok/", newsapp2, name="newsapp2"),
]

newsroom/urls.py
from django.urls import path
from .views import newsroom

urlpatterns = [
    path("", newsroom, name="newsroom"),
]

team6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("homepage.urls", "homepage"), namespace="homepage")),
    path("register/", include(("register.urls", "register"), namespace="register"),),
    path("donation/", include(("donation.urls", "donation"), namespace="donation"),),
    path("news/", include(("newsapp.urls", "newsapp"), namespace="newsapp")),
    path("newsroom/", include(("newsroom.urls", "newsroom"), namespace="newsroom")),
    path("testimoni/", include(("testimoni.urls", "testimoni"), namespace="testimoni")),
    path("auth/", include("social_django.urls", namespace="social")),
    path("user_login/", include(("login.urls", "login"), namespace="login")),
]

newsroom/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=200, default="haha")
    content = models.CharField(max_length=2000, default="hihi")

newsroom/views.py
from django.shortcuts import render
from .models import News

response = {}


def newsroom(request):
    response["newsroom"] = News.objects.all()
    return render(request, "newsroom/newsroom.html", response)

newsroom/templates/newsroom/newsroom.html
<!DOCTYPE html>
{% extends "homepage/layout/base.html" %}
{% load static %}
{% load static %}
<html lang="en-GB" prefix="og: http://ogp.me/ns#">
{% block content %}

<head>
	<title>Newsroom</title>
</head>

<body
	class="home page-template page-template-templates page-template-home page-template-templateshome-php page page-id-115 no-touch no-js site-scroll--inactive support-animations header-light">
	<div class="page-wrap" style="background-color: #4150af">
		<div class="site-header">
			<div class="site-header__section">
				<a class="site-logo" href="https://www.newlegend4x4.com">
			</div>

			<div class="site-header__section">
				<ul class="site-menu site-menu--header">

				</ul>
			</div>
			<a class="sidebar-toggle sidebar-toggle--header js-toggle-menu" href="#">
			</a>
		</div>

		<div class="sidebar-outer">
			<div>
				<div class="sidebar-inner">
					<h2 class="heading-upper txt-mid-small">CS-Crowdfund</h2>
				</div>
				<div class="sidebar-inner">
					<a class="sidebar-toggle sidebar-toggle--sticky js-toggle-menu" href="#"><svg
							xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
							<defs>
								<style>
									.\33 1fb3c84-ef88-4932-aae9-5b44edd0a9c6 {
										fill: #1c1c1e;
									}

									.\33 9d70cc3-db5c-43bb-920d-4373071766be {
										fill: none;
									}
								</style>
							</defs>
							<g id="d13c8c49-c4ab-4054-b00d-e062d76e1306" data-name="Layer 2">
								<g id="06464d94-cbf8-456f-8f4c-c3563cae9e52" data-name="Layer 1">
									<rect width="20" height="2" class="31fb3c84-ef88-4932-aae9-5b44edd0a9c6" />
									<rect width="20" height="2" y="9" class="31fb3c84-ef88-4932-aae9-5b44edd0a9c6" />
									<rect width="20" height="2" y="9" class="39d70cc3-db5c-43bb-920d-4373071766be"
										transform="translate(10 -4.14) rotate(45)" />
									<rect width="20" height="2" y="9" class="39d70cc3-db5c-43bb-920d-4373071766be"
										transform="translate(24.14 10) rotate(135)" />
									<rect width="20" height="2" y="18" class="31fb3c84-ef88-4932-aae9-5b44edd0a9c6" />
								</g>
							</g>
						</svg></a>
				</div>
			</div>
		</div>

		<section class="site-banner site-banner--bg site-banner--std site-banner" id="site-banner"
			style="background-image:url(https://www.habitatpinellas.org/content/uploads/DUKE-volunteer-group-WEB.jpg);">
			<div class="site-banner__txt section section--large post-styles">
				{% if user.is_authenticated %}
				<h1 class="site-banner__title">Welcome {{ user.first_name }} !</h1>
				{% else %}
				<h1 class="site-banner__title"></h1>
				{% endif %}
				<h2 class="site-banner__subtitle">Humanity Project</h2>
				<h1 class="site-banner__title">CS-Crowdfund</h1>
			</div>

			<a class="site-banner__arrow arrow arrow--light js-scroll-bottom" href="#site-banner">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 10">
					<defs>
						<style>
							.bc1c7e81-1b46-41ca-9147-1a64bcfd523a {
								fill: #1c1c1e;
							}
						</style>
					</defs>
					<g id="4aad50d4-ba3b-4c16-9c63-86db5eaef9ca" data-name="Layer 2">
						<g id="49b494f5-6519-4e0f-bb6e-15477af8372b" data-name="Layer 1">
							<polygon points="30 5 25 0 25 10 30 5" class="bc1c7e81-1b46-41ca-9147-1a64bcfd523a" />
							<rect width="2" height="25.66" x="11.83" y="-7.83"
								class="bc1c7e81-1b46-41ca-9147-1a64bcfd523a"
								transform="translate(7.83 17.83) rotate(-90)" />
						</g>
					</g>
				</svg>
			</a>
		</section>

		<section class="archive-links section-full spacing-small-top spacing-mini-bottom grid grid--fixed"
			style="background-color: #4150af">
			<a class="archive-link grid__col grid__col--6" href="{% url 'newsapp:newsapp2' %}">
				<div class="archive-link__img-outer">
					<img alt="Tsunami Palu" class="archive-link__img img-full" src="{% static 'images/gempa palu.jpg' %}">
					<img alt="Tsunami Palu" class="archive-link__img archive-link__img--secondary img-full js-object-fit"
						src="{% static 'images/gempa 4.jpg' %}">
				</div>

				<div class="archive-link__txt txt-center">
					<div class="archive-link__txt-inner">
						<div class="">
							<h4 class="archive-link__title">5.9 Magnitude Earthquake Tears Lombok Apart</h4>
						</div>
					</div>
				</div>
			</a>

			<a class="archive-link grid__col grid__col--6" href="{% url 'newsapp:newsapp' %}">
				<div class="archive-link__img-outer">
					<img alt="Gempa Lombok" class="archive-link__img img-full" src="{% static 'images/gempa lombok.jpg' %}">
					<img alt="Gempa Lombok" class="archive-link__img archive-link__img--secondary img-full js-object-fit"
						src="{% static 'images/gempa palu 2.jpg' %}">
				</div>

				<div class="archive-link__txt txt-center">
					<div class="archive-link__txt-inner">
						<div class="">
							<h4 class="archive-link__title">Tsunami and Earthquake Strikes Palu</h4>
							<h5 class="archive-link__subtitle heading-upper txt-mid-small spacing-mini-top"></h5>
						</div>
					</div>
				</div>
			</a>
		</section>

		<section class="section-full" style="background-color: #4150af">
			<div class="featured-slider-outer spacing-large-top"
				style="background-image: url(gempa-3-ConvertImage.jpg)">
				<div class="section section--large grid grid--spaced spacing-huge spacing-m-none-top">
					<div class="grid__col grid__col--6 grid__col--tb1-0 grid__col--tb2-0 grid__col--m-0"></div>

					<div class="grid__col grid__col--6 grid__col--tb1-12 grid__col--tb2-12 grid__col--m-12">
						<h2 class="heading-upper txt-mid txt-light">Fresh Earthquakes Strike Disaster-Hit Indonesia</h2>

						<div class="txt-large txt-gray">
							<p>Earthquakes continued to rattle Indonesia Tuesday, with fresh tremors registered in
								disaster-wracked Sulawesi and in
								another island to the south, according to the U.S. Geological Survey (USGS). The latest
								jolts come four days after a
								powerful quake and tsunami claimed at least 1,234 lives, officials say.

								Tuesday’s quakes struck in rapid succession early in the morning.

								In Sumba, an island of 750,000 people, the jolts began just after 7 a.m. local time.
								Over the next hour, the quakes
								escalated until a 6.0-magnitude tremor struck around 8 a.m., followed by a 5.9-magnitude
								quake 15 minutes later. Two
								smaller tremors followed in the afternoon.

								“People were panicking when the first quake happened and ran out of the hotel,” Defis
								Rinaldi, a staffer at the
								Padadita Beach Hotel, told Agence France-Presse.
							</p>
						</div>

						<p>
							<a class="btn-arrow txt-upper txt-small txt-light arrow--light" href="/our-story"> <span
									class="arrow arrow--inline"><svg xmlns="http://www.w3.org/2000/svg"
										viewBox="0 0 30 10">
										<defs>
											<style>
												.bc1c7e81-1b46-41ca-9147-1a64bcfd523a {
													fill: #1c1c1e;
												}
											</style>
										</defs>
										<g id="4aad50d4-ba3b-4c16-9c63-86db5eaef9ca" data-name="Layer 2">
											<g id="49b494f5-6519-4e0f-bb6e-15477af8372b" data-name="Layer 1">
												<polygon points="30 5 25 0 25 10 30 5"
													class="bc1c7e81-1b46-41ca-9147-1a64bcfd523a" />
												<rect width="2" height="25.66" x="11.83" y="-7.83"
													class="bc1c7e81-1b46-41ca-9147-1a64bcfd523a"
													transform="translate(7.83 17.83) rotate(-90)" />
											</g>
										</g>
									</svg></span></a>
						</p>
					</div>
				</div>
			</div>
		</section>

		<script type='text/javascript'
			src='https://www.newlegend4x4.com/wp-content/themes/new-legend/assets/js/min/all.min.js?ver=1537947052'></script>
		<script type='text/javascript'>
			/* <![CDATA[ */
			var ajax_data = { "ajax_admin": "https:\/\/www.newlegend4x4.com\/wp-admin\/admin-ajax.php", "security": "ec631714ef" };
/* ]]> */
		</script>
		<script type='text/javascript'
			src='https://www.newlegend4x4.com/wp-content/themes/new-legend/assets/js/min/ajax.min.js?ver=1537947052'></script>
		<script type='text/javascript' src='https://www.newlegend4x4.com/wp-includes/js/wp-embed.min.js'></script>

		<script type="text/javascript">
			if ($('#instafeed').length) {

				var feed = new Instafeed({
					get: 'user',
					userId: 4660051007,
					accessToken: '4660051007.1677ed0.bf758507dd88498bbfa421399c809631',
					resolution: 'standard_resolution',
					template: '<a class="instafeed__item" href="{{link}}" target="_BLANK"><img class="img-full" src="{{image}}" alt="{{caption}}"><span class="instafeed__item-icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><style>.\35 9e5367f-029d-41cb-a055-374bcb8cfc4f{fill:#1c1c1e;}</style></defs><g id="aa96a2e4-ffa7-495e-bc25-1995312872e6" data-name="Layer 2"><g id="52e73c27-e730-4791-884f-90a822eb50ad" data-name="Layer 1"><path d="M10 1.8c2.67 0 3 0 4 .06a5.61 5.61 0 0 1 1.86.34 3.33 3.33 0 0 1 1.9 1.9 5.61 5.61 0 0 1 .38 1.9c.05 1 .06 1.37.06 4s0 3-.06 4a5.61 5.61 0 0 1-.34 1.86 3.33 3.33 0 0 1-1.9 1.9 5.61 5.61 0 0 1-1.86.34c-1 .05-1.37.06-4 .06s-3 0-4-.06a5.61 5.61 0 0 1-1.94-.3 3.33 3.33 0 0 1-1.9-1.9 5.61 5.61 0 0 1-.34-1.9c-.05-1-.06-1.37-.06-4s0-3 .06-4a5.61 5.61 0 0 1 .34-1.9 3.33 3.33 0 0 1 1.9-1.9A5.61 5.61 0 0 1 6 1.86c1-.05 1.37-.06 4-.06M10 0C7.28 0 6.94 0 5.88.06a7.59 7.59 0 0 0-2.43.46 4.85 4.85 0 0 0-1.77 1.16A4.85 4.85 0 0 0 .52 3.45a7.59 7.59 0 0 0-.46 2.43C0 6.94 0 7.28 0 10s0 3.06.06 4.12a7.59 7.59 0 0 0 .46 2.43 4.85 4.85 0 0 0 1.16 1.77 4.85 4.85 0 0 0 1.77 1.16 7.59 7.59 0 0 0 2.43.46C6.94 20 7.28 20 10 20s3.06 0 4.12-.06a7.59 7.59 0 0 0 2.43-.46 5.19 5.19 0 0 0 2.93-2.93 7.59 7.59 0 0 0 .46-2.43c0-1.06.06-1.4.06-4.12s0-3.06-.06-4.12a7.59 7.59 0 0 0-.46-2.43 4.85 4.85 0 0 0-1.16-1.77A4.85 4.85 0 0 0 16.55.52a7.59 7.59 0 0 0-2.43-.46C13.06 0 12.72 0 10 0z" class="59e5367f-029d-41cb-a055-374bcb8cfc4f"/><path d="M10 4.86A5.14 5.14 0 1 0 15.14 10 5.14 5.14 0 0 0 10 4.86zm0 8.47A3.33 3.33 0 1 1 13.33 10 3.33 3.33 0 0 1 10 13.33z" class="59e5367f-029d-41cb-a055-374bcb8cfc4f"/><circle cx="15.34" cy="4.66" r="1.2" class="59e5367f-029d-41cb-a055-374bcb8cfc4f"/></g></g></svg></span></a>',
					limit: 5
				});

				feed.run();
			}
		</script>
</body>
{% endblock %}

</html>